import { SystemRole } from '@/modules/shared/types/auth'

export type AuditSeverity = 'low' | 'medium' | 'high' | 'critical'

export type AuditActionType =
  | 'LOGIN'
  | 'LOGOUT'
  | 'USER_CREATED'
  | 'USER_ROLE_CHANGED'
  | 'TENANT_CREATED'
  | 'TENANT_UPDATED'
  | 'CAMERA_CREATED'
  | 'CAMERA_CONFIG_CHANGED'
  | 'IA_CONFIG_CHANGED'
  | 'ALERT_RULE_CHANGED'
  | 'INFRA_SERVER_ADDED'
  | 'INFRA_SERVER_UPDATED'
  | 'INFRA_SERVER_REMOVED'
  | 'ACCESS_TEMP_GRANTED'
  | 'ACCESS_TEMP_REVOKED'

export type AuditOrigin = 'WEB' | 'API' | 'SCRIPT' | 'SYSTEM'

export type AuditResourceType = 'USER' | 'TENANT' | 'CAMERA' | 'IA' | 'ALERT_RULE' | 'INFRA'

export interface AuditEvent {
  id: string
  timestamp: string
  actorName: string
  actorEmail: string
  actorRole: SystemRole
  tenantId?: string
  tenantName?: string
  actionType: AuditActionType
  severity: AuditSeverity
  description: string
  origin: AuditOrigin
  ipAddress?: string
  userAgent?: string
  resourceType?: AuditResourceType
  resourceId?: string
  resourceName?: string
  diffSummary?: string
}

export const AUDIT_ACTION_LABELS: Record<AuditActionType, string> = {
  LOGIN: 'Login efetuado',
  LOGOUT: 'Logout realizado',
  USER_CREATED: 'Usuário criado',
  USER_ROLE_CHANGED: 'Papel de usuário editado',
  TENANT_CREATED: 'Tenant criado',
  TENANT_UPDATED: 'Tenant atualizado',
  CAMERA_CREATED: 'Câmera cadastrada',
  CAMERA_CONFIG_CHANGED: 'Configuração de câmera alterada',
  IA_CONFIG_CHANGED: 'Configuração de IA alterada',
  ALERT_RULE_CHANGED: 'Regra de alerta ajustada',
  INFRA_SERVER_ADDED: 'Servidor de infra adicionado',
  INFRA_SERVER_UPDATED: 'Servidor de infra atualizado',
  INFRA_SERVER_REMOVED: 'Servidor de infra removido',
  ACCESS_TEMP_GRANTED: 'Acesso temporário concedido',
  ACCESS_TEMP_REVOKED: 'Acesso temporário revogado',
}

export const AUDIT_REFERENCE_TIMESTAMP = Date.UTC(2025, 11, 10, 15, 30) // 10 Dez 2025 12:30 BRT

const hoursAgo = (hours: number) => new Date(AUDIT_REFERENCE_TIMESTAMP - hours * 60 * 60 * 1000).toISOString()
const minutesAgo = (minutes: number) => new Date(AUDIT_REFERENCE_TIMESTAMP - minutes * 60 * 1000).toISOString()

export const mockAuditEvents: AuditEvent[] = [
  {
    id: 'AUD-2025-0048',
    timestamp: minutesAgo(15),
    actorName: 'Lara Monteiro',
    actorEmail: 'lara.monteiro@unifique.com',
    actorRole: SystemRole.ADMIN_MASTER,
    tenantId: 'tenant-smartmall',
    tenantName: 'Smart Mall Florianópolis',
    actionType: 'ALERT_RULE_CHANGED',
    severity: 'high',
    description: 'Ajustou limite de latência da regra "Cluster lotado".',
    origin: 'WEB',
    ipAddress: '2804:14d:149:4200::25',
    userAgent: 'Chrome 121 / macOS',
    resourceType: 'ALERT_RULE',
    resourceId: 'alert-crowd-01',
    resourceName: 'Crowd Density South',
    diffSummary: 'latencyThreshold: 1200ms → 850ms',
  },
  {
    id: 'AUD-2025-0047',
    timestamp: minutesAgo(28),
    actorName: 'Diego Pacheco',
    actorEmail: 'diego.pacheco@unifique.com',
    actorRole: SystemRole.ADMIN,
    actionType: 'LOGIN',
    severity: 'low',
    description: 'Login realizado via SSO corporativo.',
    origin: 'WEB',
    ipAddress: '187.36.22.18',
    userAgent: 'Edge 120 / Windows',
  },
  {
    id: 'AUD-2025-0046',
    timestamp: minutesAgo(42),
    actorName: 'Joana Furtado',
    actorEmail: 'joana.furtado@parceiro.ai',
    actorRole: SystemRole.TECHNICIAN,
    tenantId: 'tenant-techpark',
    tenantName: 'Tech Park Joinville',
    actionType: 'ACCESS_TEMP_GRANTED',
    severity: 'medium',
    description: 'Concessão de acesso emergencial para manutenção das câmeras.',
    origin: 'WEB',
    resourceType: 'CAMERA',
    resourceId: 'cam-techpark-lobby',
    resourceName: 'Lobby Entrada 01',
    diffSummary: 'jan/10 10:00 → jan/11 10:00',
  },
  {
    id: 'AUD-2025-0045',
    timestamp: minutesAgo(55),
    actorName: 'Helena Freitas',
    actorEmail: 'helena.freitas@unifique.com',
    actorRole: SystemRole.ADMIN_MASTER,
    actionType: 'INFRA_SERVER_UPDATED',
    severity: 'critical',
    description: 'Atualizou limite de GPU do cluster IA Litoral.',
    origin: 'WEB',
    resourceType: 'INFRA',
    resourceId: 'gpu-cluster-litoral',
    resourceName: 'Cluster IA Litoral',
    diffSummary: 'gpuReservation: 70% → 82%',
  },
  {
    id: 'AUD-2025-0044',
    timestamp: hoursAgo(2),
    actorName: 'Sistema VMS',
    actorEmail: 'system@unifique.com',
    actorRole: SystemRole.ADMIN,
    actionType: 'ACCESS_TEMP_REVOKED',
    severity: 'medium',
    description: 'Revogação automática por expiração do acesso temporário do técnico.',
    origin: 'SYSTEM',
    tenantId: 'tenant-techpark',
    tenantName: 'Tech Park Joinville',
    resourceType: 'CAMERA',
    resourceId: 'cam-techpark-lobby',
    resourceName: 'Lobby Entrada 01',
  },
  {
    id: 'AUD-2025-0043',
    timestamp: hoursAgo(2.5),
    actorName: 'Marcos Bellini',
    actorEmail: 'marcos.bellini@unifique.com',
    actorRole: SystemRole.ADMIN,
    tenantId: 'tenant-smartmall',
    tenantName: 'Smart Mall Florianópolis',
    actionType: 'CAMERA_CONFIG_CHANGED',
    severity: 'medium',
    description: 'Ativou trilha de metadados para câmeras térmicas.',
    origin: 'WEB',
    resourceType: 'CAMERA',
    resourceId: 'cam-smartmall-rooftop',
    resourceName: 'Rooftop Oeste',
    diffSummary: 'metadados térmicos: inativo → ativo',
  },
  {
    id: 'AUD-2025-0042',
    timestamp: hoursAgo(3),
    actorName: 'Bruno S. Alves',
    actorEmail: 'bruno.alves@alphacase.com',
    actorRole: SystemRole.CLIENT_MASTER,
    tenantId: 'tenant-alphacase',
    tenantName: 'Alpha Case Data Center',
    actionType: 'TENANT_UPDATED',
    severity: 'low',
    description: 'Atualizou contato principal do tenant.',
    origin: 'WEB',
    resourceType: 'TENANT',
    resourceId: 'tenant-alphacase',
    resourceName: 'Alpha Case Data Center',
  },
  {
    id: 'AUD-2025-0041',
    timestamp: hoursAgo(3.2),
    actorName: 'Equipe DevOps',
    actorEmail: 'devops@unifique.com',
    actorRole: SystemRole.ADMIN,
    actionType: 'INFRA_SERVER_ADDED',
    severity: 'high',
    description: 'Provisionou nó de gravação NVMe cluster oeste.',
    origin: 'SCRIPT',
    resourceType: 'INFRA',
    resourceId: 'rec-node-west-07',
    resourceName: 'Recorder West 07',
  },
  {
    id: 'AUD-2025-0040',
    timestamp: hoursAgo(3.5),
    actorName: 'Lara Monteiro',
    actorEmail: 'lara.monteiro@unifique.com',
    actorRole: SystemRole.ADMIN_MASTER,
    actionType: 'USER_ROLE_CHANGED',
    severity: 'medium',
    description: 'Elevou permissões do gestor regional.',
    origin: 'WEB',
    resourceType: 'USER',
    resourceId: 'usr-claudio-ramos',
    resourceName: 'Cláudio Ramos',
    diffSummary: 'CLIENT_MANAGER → CLIENT_MASTER',
  },
  {
    id: 'AUD-2025-0039',
    timestamp: hoursAgo(4),
    actorName: 'Cláudio Ramos',
    actorEmail: 'claudio.ramos@varejonorte.com',
    actorRole: SystemRole.CLIENT_MASTER,
    actionType: 'LOGIN',
    severity: 'low',
    description: 'Login aprovado (MFA).',
    origin: 'WEB',
    tenantId: 'tenant-varejo-norte',
    tenantName: 'Varejo Norte',
    ipAddress: '170.80.22.11',
    userAgent: 'Safari iOS 18',
  },
  {
    id: 'AUD-2025-0038',
    timestamp: hoursAgo(4.2),
    actorName: 'Cláudio Ramos',
    actorEmail: 'claudio.ramos@varejonorte.com',
    actorRole: SystemRole.CLIENT_MASTER,
    actionType: 'CAMERA_CREATED',
    severity: 'medium',
    description: 'Cadastrou câmera de self-checkout 05.',
    origin: 'WEB',
    tenantId: 'tenant-varejo-norte',
    tenantName: 'Varejo Norte',
    resourceType: 'CAMERA',
    resourceId: 'cam-vn-sco-05',
    resourceName: 'Self Checkout 05',
  },
  {
    id: 'AUD-2025-0037',
    timestamp: hoursAgo(4.8),
    actorName: 'Equipe AI OPS',
    actorEmail: 'ai.ops@unifique.com',
    actorRole: SystemRole.ADMIN,
    actionType: 'IA_CONFIG_CHANGED',
    severity: 'high',
    description: 'Reconfigurou pipeline de detecção de intrusão para condomínios.',
    origin: 'SCRIPT',
    tenantId: 'tenant-condominio-sul',
    tenantName: 'Condomínio Sul Atlântico',
    resourceType: 'IA',
    resourceId: 'ia-intrusion-02',
    resourceName: 'Intrusão Cond. Sul',
    diffSummary: 'sensibilidade: 0.72 → 0.81',
  },
  {
    id: 'AUD-2025-0036',
    timestamp: hoursAgo(5.2),
    actorName: 'Sistema VMS',
    actorEmail: 'system@unifique.com',
    actorRole: SystemRole.ADMIN,
    actionType: 'LOGOUT',
    severity: 'low',
    description: 'Sessão expirada automaticamente.',
    origin: 'SYSTEM',
    tenantId: 'tenant-smartmall',
    tenantName: 'Smart Mall Florianópolis',
  },
  {
    id: 'AUD-2025-0035',
    timestamp: hoursAgo(5.5),
    actorName: 'Cláudia Medeiros',
    actorEmail: 'claudia.medeiros@unifique.com',
    actorRole: SystemRole.ADMIN_MASTER,
    actionType: 'TENANT_CREATED',
    severity: 'high',
    description: 'Onboarding do cliente Aeroparque Porto Alegre.',
    origin: 'WEB',
    resourceType: 'TENANT',
    resourceId: 'tenant-aeroparque',
    resourceName: 'Aeroparque Porto Alegre',
  },
  {
    id: 'AUD-2025-0034',
    timestamp: hoursAgo(6),
    actorName: 'Rafael Koch',
    actorEmail: 'rafael.koch@unifique.com',
    actorRole: SystemRole.ADMIN,
    actionType: 'ALERT_RULE_CHANGED',
    severity: 'medium',
    description: 'Alterou janela de silêncio para alertas de fumaça IA.',
    origin: 'WEB',
    resourceType: 'ALERT_RULE',
    resourceId: 'alert-smoke-03',
    resourceName: 'IA Fumaça - Galpões',
    diffSummary: 'cooldown: 15 min → 8 min',
  },
  {
    id: 'AUD-2025-0033',
    timestamp: hoursAgo(6.5),
    actorName: 'Equipe DevOps',
    actorEmail: 'devops@unifique.com',
    actorRole: SystemRole.ADMIN,
    actionType: 'INFRA_SERVER_REMOVED',
    severity: 'high',
    description: 'Descomissionou servidor legado DVR-04.',
    origin: 'SCRIPT',
    resourceType: 'INFRA',
    resourceId: 'dvr-04',
    resourceName: 'Recorder Legacy 04',
    diffSummary: 'status: active → retired',
  },
  {
    id: 'AUD-2025-0032',
    timestamp: hoursAgo(7),
    actorName: 'Lara Monteiro',
    actorEmail: 'lara.monteiro@unifique.com',
    actorRole: SystemRole.ADMIN_MASTER,
    actionType: 'USER_CREATED',
    severity: 'medium',
    description: 'Novo admin regional cadastrado.',
    origin: 'WEB',
    resourceType: 'USER',
    resourceId: 'usr-nadia-silva',
    resourceName: 'Nádia Silva',
  },
  {
    id: 'AUD-2025-0031',
    timestamp: hoursAgo(7.5),
    actorName: 'Nádia Silva',
    actorEmail: 'nadia.silva@unifique.com',
    actorRole: SystemRole.ADMIN,
    actionType: 'LOGIN',
    severity: 'low',
    description: 'Primeiro login após convite.',
    origin: 'WEB',
    ipAddress: '168.194.24.55',
    userAgent: 'Firefox 120 / Linux',
  },
  {
    id: 'AUD-2025-0030',
    timestamp: hoursAgo(8),
    actorName: 'Marcelo Prado',
    actorEmail: 'marcelo.prado@unifique.com',
    actorRole: SystemRole.ADMIN,
    tenantId: 'tenant-aquarius',
    tenantName: 'Residencial Aquarius',
    actionType: 'CAMERA_CONFIG_CHANGED',
    severity: 'medium',
    description: 'Atualizou máscara de privacidade do bloco B.',
    origin: 'WEB',
    resourceType: 'CAMERA',
    resourceId: 'cam-aqua-b2',
    resourceName: 'Bloco B - Acesso',
  },
  {
    id: 'AUD-2025-0029',
    timestamp: hoursAgo(8.3),
    actorName: 'Plataforma VMS',
    actorEmail: 'system@unifique.com',
    actorRole: SystemRole.ADMIN,
    tenantId: 'tenant-aquarius',
    tenantName: 'Residencial Aquarius',
    actionType: 'IA_CONFIG_CHANGED',
    severity: 'high',
    description: 'Rollback automático de modelo IA por drift.',
    origin: 'SYSTEM',
    resourceType: 'IA',
    resourceId: 'ia-drift-rollback-01',
    resourceName: 'Detector de placas - Aquarius',
    diffSummary: 'modelo v4.3 → v4.2 (estável)',
  },
  {
    id: 'AUD-2025-0028',
    timestamp: hoursAgo(8.8),
    actorName: 'Joana Furtado',
    actorEmail: 'joana.furtado@parceiro.ai',
    actorRole: SystemRole.TECHNICIAN,
    actionType: 'ACCESS_TEMP_GRANTED',
    severity: 'medium',
    description: 'Solicitou extensão do acesso técnico (aprovado).',
    origin: 'WEB',
    tenantId: 'tenant-techpark',
    tenantName: 'Tech Park Joinville',
    resourceType: 'TENANT',
    resourceId: 'tenant-techpark',
    resourceName: 'Tech Park Joinville',
    diffSummary: 'vigência +48h',
  },
  {
    id: 'AUD-2025-0027',
    timestamp: hoursAgo(9.5),
    actorName: 'Helena Freitas',
    actorEmail: 'helena.freitas@unifique.com',
    actorRole: SystemRole.ADMIN_MASTER,
    actionType: 'INFRA_SERVER_ADDED',
    severity: 'high',
    description: 'Incluiu servidor GPU para IA de mobilidade urbana.',
    origin: 'WEB',
    resourceType: 'INFRA',
    resourceId: 'gpu-city-09',
    resourceName: 'GPU CitySense 09',
  },
  {
    id: 'AUD-2025-0026',
    timestamp: hoursAgo(10),
    actorName: 'Equipe DevOps',
    actorEmail: 'devops@unifique.com',
    actorRole: SystemRole.ADMIN,
    actionType: 'INFRA_SERVER_UPDATED',
    severity: 'medium',
    description: 'Atualizou firmware do storage NVMe cluster sudeste.',
    origin: 'SCRIPT',
    resourceType: 'INFRA',
    resourceId: 'storage-se-04',
    resourceName: 'Storage NVMe SE-04',
  },
  {
    id: 'AUD-2025-0025',
    timestamp: hoursAgo(11),
    actorName: 'Gabriel Nogueira',
    actorEmail: 'gabriel.nogueira@unifique.com',
    actorRole: SystemRole.ADMIN,
    actionType: 'TENANT_UPDATED',
    severity: 'low',
    description: 'Atualizou SLA do contrato Varejo Norte.',
    origin: 'WEB',
    resourceType: 'TENANT',
    resourceId: 'tenant-varejo-norte',
    resourceName: 'Varejo Norte',
    diffSummary: 'SLA reação: 12h → 6h',
  },
  {
    id: 'AUD-2025-0024',
    timestamp: hoursAgo(12),
    actorName: 'Cláudio Ramos',
    actorEmail: 'claudio.ramos@varejonorte.com',
    actorRole: SystemRole.CLIENT_MASTER,
    actionType: 'CAMERA_CONFIG_CHANGED',
    severity: 'medium',
    description: 'Alterou prioridade da câmera de docas.',
    origin: 'WEB',
    tenantId: 'tenant-varejo-norte',
    tenantName: 'Varejo Norte',
    resourceType: 'CAMERA',
    resourceId: 'cam-vn-dock-01',
    resourceName: 'Docas 01',
    diffSummary: 'prioridade: média → alta',
  },
  {
    id: 'AUD-2025-0023',
    timestamp: hoursAgo(13),
    actorName: 'Sistema VMS',
    actorEmail: 'system@unifique.com',
    actorRole: SystemRole.ADMIN,
    actionType: 'ALERT_RULE_CHANGED',
    severity: 'medium',
    description: 'Correção automática de limite inválido (tenant Cond. Sul).',
    origin: 'SYSTEM',
    tenantId: 'tenant-condominio-sul',
    tenantName: 'Condomínio Sul Atlântico',
    resourceType: 'ALERT_RULE',
    resourceId: 'alert-cond-heat',
    resourceName: 'Heat Spot Garagem',
  },
  {
    id: 'AUD-2025-0022',
    timestamp: hoursAgo(14),
    actorName: 'Marcos Bellini',
    actorEmail: 'marcos.bellini@unifique.com',
    actorRole: SystemRole.ADMIN,
    actionType: 'USER_ROLE_CHANGED',
    severity: 'medium',
    description: 'Reduziu privilégios de técnico terceirizado.',
    origin: 'WEB',
    resourceType: 'USER',
    resourceId: 'usr-joana-furtado',
    resourceName: 'Joana Furtado',
    diffSummary: 'TECHNICIAN → CLIENT_MANAGER (temporário)',
  },
  {
    id: 'AUD-2025-0021',
    timestamp: hoursAgo(15),
    actorName: 'Lara Monteiro',
    actorEmail: 'lara.monteiro@unifique.com',
    actorRole: SystemRole.ADMIN_MASTER,
    actionType: 'ACCESS_TEMP_GRANTED',
    severity: 'medium',
    description: 'Liberou acesso por 24h para auditoria externa.',
    origin: 'WEB',
    tenantId: 'tenant-aeroparque',
    tenantName: 'Aeroparque Porto Alegre',
    resourceType: 'TENANT',
    resourceId: 'tenant-aeroparque',
    resourceName: 'Aeroparque Porto Alegre',
  },
  {
    id: 'AUD-2025-0020',
    timestamp: hoursAgo(16),
    actorName: 'André Teles',
    actorEmail: 'andre.teles@unifique.com',
    actorRole: SystemRole.ADMIN,
    actionType: 'ALERT_RULE_CHANGED',
    severity: 'high',
    description: 'Elevou severidade padrão de detecção de armas.',
    origin: 'WEB',
    resourceType: 'ALERT_RULE',
    resourceId: 'alert-weapon-01',
    resourceName: 'Detecção de armas global',
    diffSummary: 'severity: HIGH → CRITICAL',
  },
  {
    id: 'AUD-2025-0019',
    timestamp: hoursAgo(17),
    actorName: 'Equipe AI OPS',
    actorEmail: 'ai.ops@unifique.com',
    actorRole: SystemRole.ADMIN,
    actionType: 'IA_CONFIG_CHANGED',
    severity: 'critical',
    description: 'Deploy emergencial de modelo fallback (infra alerta).',
    origin: 'SCRIPT',
    resourceType: 'IA',
    resourceId: 'ia-fallback-urg-01',
    resourceName: 'Fallback IA Intrusão',
    diffSummary: 'modelo v5.1 → v4.9',
  },
  {
    id: 'AUD-2025-0018',
    timestamp: hoursAgo(18),
    actorName: 'Gabriel Nogueira',
    actorEmail: 'gabriel.nogueira@unifique.com',
    actorRole: SystemRole.ADMIN,
    actionType: 'TENANT_CREATED',
    severity: 'high',
    description: 'Novo tenant "Campus Digital Blumenau".',
    origin: 'WEB',
    resourceType: 'TENANT',
    resourceId: 'tenant-campus-digital',
    resourceName: 'Campus Digital Blumenau',
  },
  {
    id: 'AUD-2025-0017',
    timestamp: hoursAgo(19),
    actorName: 'Campus Digital Bot',
    actorEmail: 'bot@campusdigital.com',
    actorRole: SystemRole.MANAGER,
    actionType: 'CAMERA_CREATED',
    severity: 'medium',
    description: 'API adicionou câmera outdoor norte.',
    origin: 'API',
    tenantId: 'tenant-campus-digital',
    tenantName: 'Campus Digital Blumenau',
    resourceType: 'CAMERA',
    resourceId: 'cam-campus-north',
    resourceName: 'Outdoor Norte',
  },
  {
    id: 'AUD-2025-0016',
    timestamp: hoursAgo(21),
    actorName: 'Plataforma VMS',
    actorEmail: 'system@unifique.com',
    actorRole: SystemRole.ADMIN,
    actionType: 'LOGOUT',
    severity: 'low',
    description: 'Sessão expirada (timeout).',
    origin: 'SYSTEM',
  },
  {
    id: 'AUD-2025-0015',
    timestamp: hoursAgo(22),
    actorName: 'Helena Freitas',
    actorEmail: 'helena.freitas@unifique.com',
    actorRole: SystemRole.ADMIN_MASTER,
    actionType: 'INFRA_SERVER_REMOVED',
    severity: 'high',
    description: 'Retirou nó de QA promovido para produção.',
    origin: 'WEB',
    resourceType: 'INFRA',
    resourceId: 'infra-qa-03',
    resourceName: 'QA Recorder 03',
  },
  {
    id: 'AUD-2025-0014',
    timestamp: hoursAgo(23),
    actorName: 'Equipe Segurança',
    actorEmail: 'secops@unifique.com',
    actorRole: SystemRole.ADMIN,
    actionType: 'USER_ROLE_CHANGED',
    severity: 'high',
    description: 'Rebaixou privilégios após incidente.',
    origin: 'WEB',
    resourceType: 'USER',
    resourceId: 'usr-carlos-azevedo',
    resourceName: 'Carlos Azevedo',
    diffSummary: 'ADMIN → TECHNICIAN',
  },
  {
    id: 'AUD-2025-0013',
    timestamp: hoursAgo(25),
    actorName: 'Cláudia Medeiros',
    actorEmail: 'claudia.medeiros@unifique.com',
    actorRole: SystemRole.ADMIN_MASTER,
    actionType: 'ACCESS_TEMP_GRANTED',
    severity: 'medium',
    description: 'Liberou acesso por 72h para squad LGPD.',
    origin: 'WEB',
    resourceType: 'TENANT',
    resourceId: 'tenant-smartmall',
    tenantId: 'tenant-smartmall',
    tenantName: 'Smart Mall Florianópolis',
    resourceName: 'Smart Mall Florianópolis',
  },
  {
    id: 'AUD-2025-0012',
    timestamp: hoursAgo(27),
    actorName: 'Nádia Silva',
    actorEmail: 'nadia.silva@unifique.com',
    actorRole: SystemRole.ADMIN,
    actionType: 'ALERT_RULE_CHANGED',
    severity: 'medium',
    description: 'Personalizou notificações push do tenant Aeroparque.',
    origin: 'WEB',
    tenantId: 'tenant-aeroparque',
    tenantName: 'Aeroparque Porto Alegre',
    resourceType: 'ALERT_RULE',
    resourceId: 'alert-aero-push',
    resourceName: 'Push Aeroparque',
  },
  {
    id: 'AUD-2025-0011',
    timestamp: hoursAgo(30),
    actorName: 'Equipe AI OPS',
    actorEmail: 'ai.ops@unifique.com',
    actorRole: SystemRole.ADMIN,
    actionType: 'IA_CONFIG_CHANGED',
    severity: 'high',
    description: 'Aplicou patch de explainability para modelo de filas.',
    origin: 'SCRIPT',
    resourceType: 'IA',
    resourceId: 'ia-queue-01',
    resourceName: 'Detector de Filas',
  },
  {
    id: 'AUD-2025-0010',
    timestamp: hoursAgo(35),
    actorName: 'Plataforma VMS',
    actorEmail: 'system@unifique.com',
    actorRole: SystemRole.ADMIN,
    actionType: 'LOGOUT',
    severity: 'low',
    description: 'Logout automático - autenticação técnica.',
    origin: 'SYSTEM',
  },
  {
    id: 'AUD-2025-0009',
    timestamp: hoursAgo(40),
    actorName: 'Lara Monteiro',
    actorEmail: 'lara.monteiro@unifique.com',
    actorRole: SystemRole.ADMIN_MASTER,
    actionType: 'LOGIN',
    severity: 'low',
    description: 'Autenticação com MFA (push).',
    origin: 'WEB',
    ipAddress: '2804:14d:149:4200::25',
    userAgent: 'Chrome 121 / macOS',
  },
  {
    id: 'AUD-2025-0008',
    timestamp: hoursAgo(42),
    actorName: 'Helena Freitas',
    actorEmail: 'helena.freitas@unifique.com',
    actorRole: SystemRole.ADMIN_MASTER,
    actionType: 'INFRA_SERVER_ADDED',
    severity: 'high',
    description: 'Ampliação do cluster IA Amazônia.',
    origin: 'WEB',
    resourceType: 'INFRA',
    resourceId: 'gpu-forest-04',
    resourceName: 'GPU ForestSense 04',
  },
  {
    id: 'AUD-2025-0007',
    timestamp: hoursAgo(45),
    actorName: 'Sistema VMS',
    actorEmail: 'system@unifique.com',
    actorRole: SystemRole.ADMIN,
    actionType: 'ACCESS_TEMP_REVOKED',
    severity: 'medium',
    description: 'Acesso técnico revogado (detectado inatividade).',
    origin: 'SYSTEM',
    resourceType: 'TENANT',
    resourceId: 'tenant-techpark',
    tenantId: 'tenant-techpark',
    tenantName: 'Tech Park Joinville',
    resourceName: 'Tech Park Joinville',
  },
  {
    id: 'AUD-2025-0006',
    timestamp: hoursAgo(48),
    actorName: 'Equipe Segurança',
    actorEmail: 'secops@unifique.com',
    actorRole: SystemRole.ADMIN,
    actionType: 'USER_CREATED',
    severity: 'medium',
    description: 'Criou usuário para auditoria LGPD.',
    origin: 'WEB',
    resourceType: 'USER',
    resourceId: 'usr-lucas-vieira',
    resourceName: 'Lucas Vieira',
  },
  {
    id: 'AUD-2025-0005',
    timestamp: hoursAgo(54),
    actorName: 'Lucas Vieira',
    actorEmail: 'lucas.vieira@auditoria.com',
    actorRole: SystemRole.TECHNICIAN,
    actionType: 'LOGIN',
    severity: 'low',
    description: 'Login aprovado (token temporário).',
    origin: 'WEB',
    ipAddress: '189.122.66.80',
    userAgent: 'Chrome 120 / Windows',
  },
  {
    id: 'AUD-2025-0004',
    timestamp: hoursAgo(60),
    actorName: 'Lucas Vieira',
    actorEmail: 'lucas.vieira@auditoria.com',
    actorRole: SystemRole.TECHNICIAN,
    actionType: 'ACCESS_TEMP_GRANTED',
    severity: 'medium',
    description: 'Solicitou acesso para vistoria LGPD (aprovado).',
    origin: 'WEB',
    resourceType: 'TENANT',
    resourceId: 'tenant-smartmall',
    tenantId: 'tenant-smartmall',
    tenantName: 'Smart Mall Florianópolis',
    resourceName: 'Smart Mall Florianópolis',
  },
  {
    id: 'AUD-2025-0003',
    timestamp: hoursAgo(80),
    actorName: 'Sistema VMS',
    actorEmail: 'system@unifique.com',
    actorRole: SystemRole.ADMIN,
    actionType: 'ACCESS_TEMP_REVOKED',
    severity: 'medium',
    description: 'Revogou acesso expirado do auditor LGPD.',
    origin: 'SYSTEM',
    resourceType: 'TENANT',
    resourceId: 'tenant-smartmall',
    tenantId: 'tenant-smartmall',
    tenantName: 'Smart Mall Florianópolis',
    resourceName: 'Smart Mall Florianópolis',
  },
  {
    id: 'AUD-2025-0002',
    timestamp: hoursAgo(95),
    actorName: 'Helena Freitas',
    actorEmail: 'helena.freitas@unifique.com',
    actorRole: SystemRole.ADMIN_MASTER,
    actionType: 'INFRA_SERVER_UPDATED',
    severity: 'medium',
    description: 'Mudou perfil de energia do cluster streaming centro.',
    origin: 'WEB',
    resourceType: 'INFRA',
    resourceId: 'stream-core-02',
    resourceName: 'Streaming Core 02',
  },
  {
    id: 'AUD-2025-0001',
    timestamp: hoursAgo(120),
    actorName: 'Helena Freitas',
    actorEmail: 'helena.freitas@unifique.com',
    actorRole: SystemRole.ADMIN_MASTER,
    actionType: 'LOGIN',
    severity: 'low',
    description: 'Login diário Admin Master.',
    origin: 'WEB',
    ipAddress: '2804:14d:149:1111::52',
    userAgent: 'Chrome 120 / macOS',
  },
]

export type AuditKpiStats = {
  eventsLast24h: number
  severeEvents: number
  distinctUsers24h: number
  productionChanges: number
}

export function buildAuditKpis(events: AuditEvent[], referenceTimestamp: number = AUDIT_REFERENCE_TIMESTAMP): AuditKpiStats {
  const dayAgo = referenceTimestamp - 24 * 60 * 60 * 1000

  const last24h = events.filter((event) => new Date(event.timestamp).getTime() >= dayAgo)
  const severeEvents = last24h.filter((event) => event.severity === 'high' || event.severity === 'critical').length
  const distinctUsers = new Set(last24h.map((event) => event.actorEmail)).size
  const productionChanges = last24h.filter((event) => ['IA', 'ALERT_RULE', 'INFRA'].includes(event.resourceType ?? '')).length

  return {
    eventsLast24h: last24h.length,
    severeEvents,
    distinctUsers24h: distinctUsers,
    productionChanges,
  }
}

export function getUniqueAuditTenants(events: AuditEvent[]): Array<{ id: string; name: string }> {
  const map = new Map<string, string>()
  events.forEach((event) => {
    if (event.tenantId && event.tenantName) {
      map.set(event.tenantId, event.tenantName)
    }
  })
  return Array.from(map.entries()).map(([id, name]) => ({ id, name })).sort((a, b) => a.name.localeCompare(b.name))
}
