import { SystemRole } from '@/modules/shared/types/auth'
import { ROLE_LABELS } from '@/modules/shared/types/roleLabels'

import type { RoleAccessConfig } from './roleTypes'

export const DEFAULT_ROLE_PERMISSIONS: RoleAccessConfig[] = [
  {
    role: SystemRole.ADMIN_MASTER,
    label: ROLE_LABELS[SystemRole.ADMIN_MASTER],
    description: 'Gestão plena da plataforma, sem acesso a vídeo conforme LGPD.',
    scope: 'GLOBAL',
    permissions: {
      canViewStatus: true,
      canViewVideo: false,
      canViewVideoTemporary: false,
      canViewRecordings: false,
      canManageAdmins: true,
      canManageTechnicians: true,
      canManageClients: true,
      canManageUsers: true,
      canManageCameras: true,
      canManageIA: true,
      canManageAlerts: true,
      canManageStorage: true,
      canManageInfrastructure: true,
      canGrantTemporaryAccess: true,
    },
  },
  {
    role: SystemRole.ADMIN,
    label: ROLE_LABELS[SystemRole.ADMIN],
    description: 'Administração operacional com acesso restrito a vídeo.',
    scope: 'GLOBAL_LIMITED',
    permissions: {
      canViewStatus: true,
      canViewVideo: false,
      canViewVideoTemporary: false,
      canViewRecordings: false,
      canManageAdmins: false,
      canManageTechnicians: true,
      canManageClients: true,
      canManageUsers: true,
      canManageCameras: true,
      canManageIA: true,
      canManageAlerts: true,
      canManageStorage: false,
      canManageInfrastructure: false,
      canGrantTemporaryAccess: false,
    },
  },
  {
    role: SystemRole.TECHNICIAN,
    label: ROLE_LABELS[SystemRole.TECHNICIAN],
    description: 'Perfil técnico para instalação e suporte em campo.',
    scope: 'INSTALLATION_ONLY',
    permissions: {
      canViewStatus: true,
      canViewVideo: false,
      canViewVideoTemporary: true,
      canViewRecordings: false,
      canManageAdmins: false,
      canManageTechnicians: false,
      canManageClients: false,
      canManageUsers: false,
      canManageCameras: true,
      canManageIA: true,
      canManageAlerts: false,
      canManageStorage: false,
      canManageInfrastructure: false,
      canGrantTemporaryAccess: false,
    },
  },
  {
    role: SystemRole.CLIENT_MASTER,
    label: ROLE_LABELS[SystemRole.CLIENT_MASTER],
    description: 'Responsável máximo pelo tenant, com visão completa do vídeo.',
    scope: 'TENANT_FULL',
    permissions: {
      canViewStatus: true,
      canViewVideo: true,
      canViewVideoTemporary: false,
      canViewRecordings: true,
      canManageAdmins: false,
      canManageTechnicians: false,
      canManageClients: false,
      canManageUsers: true,
      canManageCameras: true,
      canManageIA: true,
      canManageAlerts: true,
      canManageStorage: 'viewOnly',
      canManageInfrastructure: false,
      canGrantTemporaryAccess: true,
    },
  },
  {
    role: SystemRole.MANAGER,
    label: ROLE_LABELS[SystemRole.MANAGER],
    description: 'Gestão de setores específicos com acesso limitado.',
    scope: 'SECTOR',
    permissions: {
      canViewStatus: true,
      canViewVideo: true,
      canViewVideoTemporary: false,
      canViewRecordings: 'optional',
      canManageAdmins: false,
      canManageTechnicians: false,
      canManageClients: false,
      canManageUsers: false,
      canManageCameras: 'limited',
      canManageIA: 'limited',
      canManageAlerts: 'limited',
      canManageStorage: false,
      canManageInfrastructure: false,
      canGrantTemporaryAccess: false,
    },
  },
  {
    role: SystemRole.VIEWER,
    label: ROLE_LABELS[SystemRole.VIEWER],
    description: 'Acesso somente leitura às transmissões autorizadas.',
    scope: 'VIEW_ONLY',
    permissions: {
      canViewStatus: true,
      canViewVideo: true,
      canViewVideoTemporary: false,
      canViewRecordings: 'optional',
      canManageAdmins: false,
      canManageTechnicians: false,
      canManageClients: false,
      canManageUsers: false,
      canManageCameras: false,
      canManageIA: false,
      canManageAlerts: false,
      canManageStorage: false,
      canManageInfrastructure: false,
      canGrantTemporaryAccess: false,
    },
  },
]
